"""
Django settings for orderbus project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'django_prometheus',  # Must be before other apps
    # Local apps
    'orders',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',  # After sessions
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orderbus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orderbus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_prometheus.db.backends.postgresql',  # Prometheus-instrumented DB
        'NAME': config('DB_NAME', default='orderdb'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASS', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# REST Framework Configuration
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}


# ==============================================================================
# Google Pub/Sub Configuration
# ==============================================================================

# Pub/Sub emulator host (set for local development, unset for production GCP)
PUBSUB_EMULATOR_HOST = config('PUBSUB_EMULATOR_HOST', default=None)

# Set environment variable for Google Pub/Sub client libraries
if PUBSUB_EMULATOR_HOST:
    os.environ['PUBSUB_EMULATOR_HOST'] = PUBSUB_EMULATOR_HOST

# GCP Project ID
PUBSUB_PROJECT_ID = config('PUBSUB_PROJECT_ID', default='demo-poc')

# Topic and Subscription names
PUBSUB_TOPIC_ORDER_CREATED = config('PUBSUB_TOPIC_ORDER_CREATED', default='order.created')
PUBSUB_SUBSCRIPTION_ORDER_CREATED = config(
    'PUBSUB_SUBSCRIPTION_ORDER_CREATED', default='order.created.local'
)


# ==============================================================================
# Webhook Configuration
# ==============================================================================

# Outgoing webhook URL (e.g., RequestCatcher for testing)
WEBHOOK_OUTGOING_URL = config('WEBHOOK_OUTGOING_URL', default='https://example.com/')

# Webhook secret for HMAC signature verification (ingress webhooks)
# If not set, signature verification is skipped (development only)
WEBHOOK_SECRET = config('WEBHOOK_SECRET', default=None)

# ==============================================================================
# Shopify Configuration
# ==============================================================================

SHOPIFY_ADMIN_TOKEN = config('SHOPIFY_ADMIN_TOKEN', default=None)
SHOPIFY_API_URL = config('SHOPIFY_API_URL', default=None)
SHOPIFY_API_VERSION = config('SHOPIFY_API_VERSION', default='2024-10')
SHOPIFY_API_SCOPES = config('SHOPIFY_API_SCOPES', default='read_orders,write_orders')
SHOPIFY_TIMEOUT = config('SHOPIFY_TIMEOUT', default=30)

# ==============================================================================
# OpenTelemetry Configuration
# ==============================================================================

OTEL_ENABLED = config('OTEL_ENABLED', default=True, cast=bool)
OTEL_SERVICE_NAME = config('OTEL_SERVICE_NAME', default='django-orderbus')
OTEL_EXPORTER_TYPE = config('OTEL_EXPORTER_TYPE', default='jaeger')  # 'jaeger' or 'otlp'
OTEL_EXPORTER_JAEGER_ENDPOINT = config(
    'OTEL_EXPORTER_JAEGER_ENDPOINT', default='http://localhost:14268/api/traces'
)
OTEL_EXPORTER_OTLP_ENDPOINT = config(
    'OTEL_EXPORTER_OTLP_ENDPOINT', default='http://localhost:4318/v1/traces'
)
OTEL_EXPORTER_METRICS_ENABLED = config(
    'OTEL_EXPORTER_METRICS_ENABLED', default=False, cast=bool
)
# Note: OTel metrics are exported via OTLP to Jaeger, not directly to Prometheus
JAEGER_AGENT_HOST = config('JAEGER_AGENT_HOST', default='localhost')
JAEGER_AGENT_PORT = config('JAEGER_AGENT_PORT', default=6831, cast=int)

# ==============================================================================
# Prometheus Configuration
# ==============================================================================

PROMETHEUS_EXPORT_MIGRATIONS = config('PROMETHEUS_EXPORT_MIGRATIONS', default=False, cast=bool)

# ==============================================================================
# Logging Configuration
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'orders': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'orderbus': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}