# Generated by Django 5.2.7 on 2025-10-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Idempotency key to prevent duplicate processing",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
